# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_aggregate_root}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Surya Gaddipati"]
  s.date = %q{2011-01-30}
  s.description = %q{Automatically manages saving, deletion and validating the object graph}
  s.email = %q{surya.gaddipati@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "acts-as-aggregate-root.gemspec",
    "acts_as_taggable_on.sqlite3",
    "lib/acts_as_aggregate_root.rb",
    "lib/acts_as_aggregate_root/acts_as_aggregate_root.rb",
    "rails/init.rb",
    "spec/acts_as_aggregate_root/acts_as_aggregate_root_spec.rb",
    "spec/bm.rb",
    "spec/database.yml",
    "spec/debug.log",
    "spec/order.rb",
    "spec/order_item.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "spec/sub_order.rb"
  ]
  s.homepage = %q{http://github.com/suryagaddipati/acts-as-aggregate-root}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Makes an active record object act as an aggregate root}
  s.test_files = [
    "spec/acts_as_aggregate_root/acts_as_aggregate_root_spec.rb",
    "spec/bm.rb",
    "spec/order.rb",
    "spec/order_item.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "spec/sub_order.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 2.3.5"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<mysql>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 2.3.5"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 2.3.5"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
  end
end

